### ISSUE TITLE
performance waarnemingen Zeeland

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#20]
Test query tbv performance onderzoek waarnemingen:
62778 waarnemingen
op db total execution time 761

Query die uit CRS2 naar de viewer wordt gestuurd:

SELECT Wrn.wrn_pk AS id, Wrn.wrn_pk, Wrn.ogr_geometry AS geom 
FROM Wrn WHERE wrn_pk > 0 
AND wrn_pk IN 
( SELECT wrn_pk FROM wrn, obj, bhr, dis, loc, mth, opr, sgp, grp, hgp, abu, gsl, ddo, dom, std, vbp, vbs, soo 
        WHERE abu_pk = wrn_abu_fk 
                AND gsl_pk = wrn_gsl_fk 
                AND ddo_pk = wrn_ddo_fk 
                AND dom_pk = wrn_dom_fk 
                AND std_pk = wrn_std_fk 
                AND vbp_pk = wrn_vbp_fk 
                AND vbs_pk = wrn_vbs_fk 
                AND loc_pk = wrn_loc_fk 
                AND opr_pk = wrn_opr_fk 
                AND mth_pk = wrn_mth_fk 
                AND obj_pk = wrn_obj_fk 
                AND bhr_pk = obj_bhr_fk 
                AND dis_pk = bhr_dis_fk 
                AND soo_pk = wrn_soo_fk 
                AND sgp_pk = soo_sgp_fk 
                AND grp_pk = sgp_grp_fk 
                AND hgp_pk = grp_hgp_fk 
AND wrn.wrn_pk IN 
    (SELECT wrn.wrn_pk FROM hgp, grp, sgp, soo, wrn 
        WHERE hgp.hgp_pk = grp.grp_hgp_fk 
            AND grp.grp_pk = sgp.sgp_grp_fk 
            AND sgp.sgp_pk = soo.soo_sgp_fk 
            AND soo.soo_pk = wrn.wrn_soo_fk 
            AND RTRIM(LTRIM(hgp_oms)) = 'Planten'))

Query geoptimaliseerd (geeft niet zelfde aantal resultaten!) :
62831 waarnemingen
op db total execution time 221

SELECT Wrn.wrn_pk AS id, Wrn.wrn_pk, Wrn.ogr_geometry AS geom 
    FROM Wrn WHERE wrn_pk IN
    (SELECT wrn.wrn_pk FROM hgp, grp, sgp, soo, wrn 
        WHERE grp.grp_pk = sgp.sgp_grp_fk 
            AND sgp.sgp_pk = soo.soo_sgp_fk 
            AND soo.soo_pk = wrn.wrn_soo_fk 
            AND grp.grp_hgp_fk =5)

**Comment by HermanAssink** [comment]
Punten kunnen relatief eenvoudig geclusterd worden door coördinaten af te ronden met een schaalafhankelijke afstand. Deze afstand moet dan in onderstaande voorbeeld-query worden ingevuld i.p.v. "1000"

SELECT MAX(wrn_rnd.wrn_pk) id, COUNT(*) cluster_size, geometry::Point(wrn_rnd.cluster_x, wrn_rnd.cluster_y, 0) as geom
FROM (SELECT WRN.WRN_PK, ROUND(ogr_geometry.STX / 1000, 0) \* 1000 as cluster_x, 
       ROUND(ogr_geometry.STY / 1000, 0) \* 1000 as cluster_y
       From WRN where wrn.ogr_geometry is not null) wrn_rnd
GROUP BY cluster_x, cluster_y

**Comment by kad-velsl** [comment]
Na een snelle test op de testserver blijkt de huidige oplossing nog niet te voldoen:
- Bij het maken van een selectie worden geselecteerde features anders geclusterd dan de niet geselecteerd features, dit resulteert in een kaartbeeld waarin geselecteerde features en niet geselecteerde door elkaar heen worden getekend waar je alleen geselecteerde features verwacht.
- Een selectie vanuit het CRS2 scherm resulteert in een leeg kaartbeeld.

**Comment by kad-velsl** [comment]
testen

**Comment by kad-velsl** [comment]
Huidige oplossing: Alleen geselecteerde waarnemingen tonen.

Probleem: Bij het selecteren met een geometrie in de viewer wordt vrij snel het kaartbeeld ververst maar het duurt daarna nog erg lang voordat de onSelectionChanged afgaat. Het lijkt erop dat de WFS de query langzaam afhandelt. Ook treden er (na verloop van tijd?) TimeOut fouten op in Akka en lijkt het systeem geblokkeerd.

Verschil tussen WMS en WFS is de BBox die bij de selectie meegenomen wordt. Misschien is het een idee om dit te faken bij een WFS query.

**Comment by copierrj** [comment]
Je geeft aan dat het **lijkt** alsof de WFS langzaam is. Heb je dit experimenteel aangetoond? Vergelijk ook eens de performance van de onderliggende SQL queries (WMS en WFS) zoals die naar de database gaan.

**Comment by kad-velsl** [comment]
Probleem opgelost door bij een  kaart service request zonder BBOX de laatste whereclause weg te laten. Kennelijk kan SQLserver niet goed omgaan met een innerquery met een spatial filter met dooromheen een BBOX filter.
