### ISSUE TITLE
zoomen op eigen server

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#25]
Limburg:
Als er ingezoomd word met vergrootglasje op een bepaald perceel dan komt dit perceel niet mooi gecentreerd in beeld. Een deel van het ingezoomde perceel ligt buiten de view.
In de test.crs2.nl werkt dit wel correct.

**Comment by kad-velsl** [comment]
testen op Limburg omgeving

**Comment by kad-velsl** [comment]
Testen op de limburg omgeving laat geen vreemd zoom gedrag zien. Ligt het misschien aan discrete schaalgrenzen?

**Comment by erikorbons** [comment]
Ik constateer dat dit het geval is wanneer een gebied waarop wordt ingezoomd mbv de zoom-tool aan de rand van het huidige kaartbeeld ligt. OpenLayers brengt dan soms niet de volledige bounding-box in beeld.

**Comment by erikorbons** [comment]
Opgelost.

Zie ook: IDgis/CRS2#140 en IDgis/CRS2#103
