### ISSUE TITLE
Releaseprocedure inrichten

### ISSUE THREAD

**Issue by erikorbons** [IDgis/geoide-develop#29]

**Comment by erikorbons** [comment]
Versienummer Play! project uitlezen uit pom, zoals bij geo-publisher?

**Comment by HermanAssink** [comment]
Een volledig geautomatiseerde releaseprocedure is niet (goed) mogelijk omdat zowel Play (SBT) als Maven wordt gebruikt. Het project zou gesplitst moeten worden in meerdere repositories voor een verbeterde releaseprocedure maar dat is lastig bij het ontwikkelen. We besluiten om de releaseprocedure zo veel mogelijk te automatiseren, bijvoorbeeld door de workaround die bij GeoPublisher is toegepast, waarbij Maven SBT aanroept, ook hier te gebruiken. Belangrijkste reden: minder foutgevoelig. Onderzoek naar de meest wenselijke oplossing is noodzakelijk.

**Comment by HermanAssink** [comment]
Hopelijk levert LinkedIn tzt een betere oplossing met Gradle.

**Comment by kad-velsl** [comment]
Gradle voor geoide-web werkt nog niet goed: een aantal files in assets worden niet gevonden zodat de viewer mbv localhost:9000 niet goed opstart

**Comment by kad-velsl** [comment]
De gradle procedure voor het laatste stukje (crs-geoide project) moet nog worden ontwikkeld
