### ISSUE TITLE
31 splitsen van crs, ca en geoide-web

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#31]
geoide-web wordt een overkoepelend project voor de projecten crs en ca. In crs en ca zit met name configuratie. Templates en kaartconfiguratie moeten van het classpath gelezen worden en niet vanaf het filesystem.

**Comment by HermanAssink** [comment]
Vraag: Heeft Geoide-web betrekking op de Foxpro specifieke zaken en de CRS en CA variant voegt alleen de CA/CRS specifieke configuratie toe?
Hoe heet de laag waar geen Foxpro specifieke zaken inzitten, maar wel de overige functionaliteit van Geoide-crs/ca?
