### ISSUE TITLE
'gemaakt door:' verschijnt niet op print

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#33]
Onderzoeken wat hier aan de hand is. 
- staat dit wel in templates 
- verschijnt dit in printscherm CRS2
  etc.

Zie IDgis/CRS2#137

**Comment by erikorbons** [comment]
Bij naspelen van dit scenario constateer ik dat de naam wel op de print komt (A4-staand). Wel valt het op dat als je wisselt van template terwijl er al iets is ingevuld in één van de velden deze waarden weer leeg worden gemaakt.

**Comment by erikorbons** [comment]
Onderliggende issue IDgis/CRS2#137 gesloten door de klant.
