### ISSUE TITLE
enter in scaleinput resulteert in toc openen/sluiten

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#35]

**Comment by erikorbons** [comment]
Te reproduceren in zowel de standalone versie als embedded in FoxPro. 

Dit gedrag treedt uitsluitend op in IE9 (en daarmee dus ook in de embedded browser in FoxPro).

**Comment by erikorbons** [comment]
"Enter" selecteert de eerste submit-knop bij drukken op enter in een form-input. Kennelijk hoeven de controls hiervoor niet in een form te staan in IE9. De knop om de TOC te openen/sluiten is de eerste knop, dus deze wordt gekozen.

Alle buttons in de toolbar zijn voorzien van type="button", voor zo ver dat nog niet was gedaan. Tevens wordt het event behorende bij de enter-toets nu afgevangen en expliciet afgehandeld door de tool, dit heeft als bijkomend voordeel dat het control niet de focus verliest bij een druk op enter.
