### ISSUE TITLE
Improving Deployment/Installation

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#4]

**Comment by kad-velsl** [comment]
- scripts bijwerken
- installatie hendleiding updaten
- deployment verbeteren (cs.zip, ...)

**Comment by erikorbons** [comment]
Verbetervoorstellen:
- Elimineren noodzaak voor Tomcat installatie en kopieren context files naar de tomcat-directory door eigen Tomcat service te maken (Tomcat embedded) en daar de webapplicaties via software aan toe te voegen. **Elimineert stappen:** tomcat installatie, inrichten kaartservices, inrichten van de CRS2 kaartlaagservices
- Play applicatie starten uit een eigen java-applicatie waarbinnen ook de Tomcat draait. Elimineert de noodzaak om de deliverable van de Play applicatie na te bewerken.
