### ISSUE TITLE
Printen loopt vast bij veel geselecteerde afdelingen

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#65]
Wannes 7/1/2016:

"Dan nog het volgende bij het printen van een kaartje, dit blijkt al snel niet mogelijk. Zodra het aantal geselecteerde records in crs hoger is dan zo maar een enkele gaat het niet meer. Dus als ik drie afdelingen geselecteerd heb en ik print een kaartje dan doet hij het wel, als ik een (pacht)kaartje met wat meer geselecteerde afdelingen wil printen werkt het niet meer. Dan krijg ik een wereldbolletje en mapje te zien die bladzijdes overgooien, maar dan kun je wachten tot…. "

**Comment by kad-velsl** [comment]
uitzoeken of dit nog speelt bij Zeeland en Kroondomeinen

**Comment by kad-velsl** [comment]
Getest op de CRS2 omgeving van Zeeland en geen problemen meer gezien. Wannes gevraagd om te bevestigen dat dit probleem inderdaad weg is.

**Comment by kad-velsl** [comment]
Op de omgeving van Kroondomeinen kunnen we niet testen. Misschien moeten we een mail sturen om te vragen of het probleem nog speelt.

**Comment by HermanAssink** [comment]
Bert Kraan heeft deze week nog gezegd dat hem geen acute problemen bekend zijn. Dus issue sluiten.
