### ISSUE TITLE
legenda plaatjes in distributie CA/CRS viewer

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#71]

**Comment by HermanAssink** [comment]
Wat is het probleem?

**Comment by kad-velsl** [comment]
Er is geen probleem maar het wrapping project moet wel de plaatjes op de juiste plaats meeleveren in de distributie (gebeurt nog niet)

**Comment by kad-velsl** [comment]
Sinds versie 1.0.11 worden de plaatjes wel meegeleverd in de distributie in de folder maps. De image provider configuratie (default) verwijst echter naar een folder images, een van twee moet worden aangepast.

**Comment by HermanAssink** [comment]
Bij voorkeur de programmatuur aanpassen zodat we bij een nieuwe versie van programmatuur niet de config map hoeven aan te passen.

**Comment by HermanAssink** [comment]
Deze issue blijkt niet te bestaan, is geen issue
