### ISSUE TITLE
Selectie style sql laag niet bovenop

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#73]

**Comment by kad-velsl** [comment]
Selectie style wordt soms wel en soms niet bovenop getekend

**Comment by kad-velsl** [comment]
Lijkt alleen op te treden bij de laag afdelingen

**Comment by kad-velsl** [comment]
de deegree configuration op lokale omgeving ververst, en service herstart. Het probleem lijkt hiermee te zijn opgelost.

**Comment by HermanAssink** [comment]
Niet gereproduceerd
