### ISSUE TITLE
zoeksuggesties werkn niet goed

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-develop#75]

**Comment by kad-velsl** [comment]
Alleen zoeksuggesties van laatste request tonen,
Zoekresultaten juist sorteren

**Comment by HermanAssink** [comment]
Na het intypen van een zoekstring zonder resultaten, bijv. HLN02C, en vervolgens deleten van de laatste karakters, de "C" in het voorbeeld, komt de suggestielijst niet terug.

**Comment by kad-velsl** [comment]
In IE9 is het input event niet volledig geïmplemeteerd. In de programmatuur een IE9 specifieke work around imgebouwd.

**Comment by HermanAssink** [comment]
Werkt nog niet, bij backspace worden de suggesties worden de suggesties niet ververst (versie: 1.1.0-RC1)

**Comment by kad-velsl** [comment]
getest in echte IE9 (geen emulatie versie) hierin werkt het, binnen CRS2 werkt het echter niet. 
Verder onderzoeken met debug meldingen op het test formulier binnen CRS2

**Comment by kad-velsl** [comment]
De IE9 binnen CRS2 bleek een net iets andere userAgent String  te adverteren waardoor de browser niet werd herkend als IE9. De code is hierop aangepast en de nieuwe versie is uitgerold voor limburg op test.crs2.nl

**Comment by HermanAssink** [comment]
Issue met niet aanpassen zoeksuggesties bij backspace is opgelost. Lijst is echter niet gesorteerd, bijv. 21\* laat geen 212\* zien, terwijl dat wel voorkomt bij afdelingen van Limburg
